#
# $Id$
#
# Copyright 2016-2017 Quantcast Corporation. All rights reserved.
#
# This file is part of Quantcast File System.
#
# Licensed under the Apache License, Version 2.0
# (the "License"); you may not use this file except in compliance with
# the License. You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or
# implied. See the License for the specific language governing
# permissions and limitations under the License.

sudo: required
language: cpp
compiler: gcc
script: travis/script.sh

before_install:
    # Travis CI's mac os environment doesn't set java home properly. This is
    # done here and not in the before_install.sh script since exporting the
    # variable in a called script won't update the caller environment scope.
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home) ; fi
    - travis/before_install.sh

os:
    - osx
    - linux

env:
    matrix:
        - DISTRO=osx           VER=none  CODECOV=no  BTYPE=release BUSER=''
        - DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=debug   BUSER=qfsbuild
        - DISTRO=ubuntu        VER=16.04 CODECOV=yes BTYPE=release BUSER=qfsbuild
        - DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=release BUSER=root
        - DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=f69m/ubuntu32 VER=16.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=ubuntu        VER=14.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=ubuntu        VER=18.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=centos        VER=5     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=centos        VER=6     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=centos        VER=7     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - DISTRO=debian        VER=9     CODECOV=no  BTYPE=release BUSER=qfsbuild

matrix:
    exclude:
        - os: osx
          env: DISTRO=ubuntu        VER=16.04 CODECOV=yes BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=debug   BUSER=qfsbuild
        - os: osx
          env: DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=release BUSER=root
        - os: osx
          env: DISTRO=ubuntu        VER=16.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=f69m/ubuntu32 VER=16.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=ubuntu        VER=14.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=ubuntu        VER=18.04 CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=centos        VER=5     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=centos        VER=6     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=centos        VER=7     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: osx
          env: DISTRO=debian        VER=9     CODECOV=no  BTYPE=release BUSER=qfsbuild
        - os: linux
          env: DISTRO=osx           VER=none  CODECOV=no  BTYPE=release BUSER=''

services:
    - docker

before_deploy:
    # Docker build might use different user or root, change ownership back to
    # the current user.
    - sudo chown `id -u`:`id -g` . build
    - mkdir artifacts
    - mv build/*.tgz artifacts

deploy:
    provider: s3
    bucket: quantcast-qfs
    skip_cleanup: true
    region: us-east-1
    local_dir: artifacts
    access_key_id:
        - secure: UqMk3DuP3phOQTNLropADqDSjFInV8+imvfU5dhevYU6ycaDeEp9PI6bIJE53nxckpED3j3CaWs8CzgHJmeQ+yC8SCoJWti5zhHb12APuPQQfOFp7vjSQsEUI29Ymaz7bqcZBODmWg5es70Zuxes9mRSBd4PzpCFvvUsBKUYYKg=
    secret_access_key:
        - secure: UOL4vCiUFALq2MwOji2dUbT9HrSw1GInFH6SfY1pN5fnanmEGgw3jRwnqTu2hu9KhFEhZq5vZDEGogRU8AVQPJjCkGQFZW/sakKuJfLKMM7qr6+mLZ8VmWr8cmVIUswosknoxplXlRx2FnuEYwbN0ju0QZFfARehR03W5Ehii8o=
    on:
        all_branches: true
        condition: "false && $CODECOV != yes && $BTYPE = release && $BUSER != root && ( $TRAVIS_BRANCH = $TRAVIS_TAG || $TRAVIS_BRANCH = master )"
