sudo: false # enable container based builds (can't use sudo)
language: cpp
script: make tarball

compiler:
    - gcc
    # - clang

os:
    - linux
    - osx

before_install:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install git || true ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install cmake || true ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install maven || true ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install boost || true ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install puppet || true ; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export JAVA_HOME=$(/usr/libexec/java_home) ; fi

before_deploy:
    - mkdir artifacts
    - export OS=$(facter operatingsystem | awk '{print tolower($0)}')
    - export OSVERSION=$(facter operatingsystemrelease)
    - export ARCH=$(uname -i)
    - mv build/*.tgz artifacts/qfs-$OS-$OSVERSION-master-$ARCH.tgz

deploy:
    provider: s3
    bucket: quantcast-qfs
    skip_cleanup: true
    region: us-east-1
    local_dir: artifacts
    access_key_id:
        - secure: IvmQ1sHBE+/USw+/adukFk1Wxq9Pn49PTvlbbRoI1D3W+ILc7u7+rFuNwQqAexXfBP71oMEE8YDR4U9dcoD4NinMd02lciFzrbtzErQ2Re2fU6k3I2OiyJ8ApAalKLxNmFC8jPTPufFT8gfCfOjoSDIpEffA75EzJVmDdDOspvw=
    secret_access_key:
        - secure: HkCLJKSX7jUPzsbZeiK3pSwECP79q6ypRnzudsTlRzmbW/eKloJHLwPEZycAakH9S24cqgjKTvv1O8XZ8sTGx0lhonRRBOXeYN9tVKrwL7CIbDHy4fOJkVQYG321EmKr3UIL9rAYZyR01WC1hEJ6pPJK7xgcFTDhZ0e47wegUlI=

addons:
    apt:
        packages:
            - git
            - cmake
            - libboost-regex-dev
            - xfslibs-dev
            - libssl-dev
            - default-jdk
            - python-dev
            - fuse-dev
            - puppet # not a qfs dependency, but for facter above

notifications:
    email:
        recipients:
            - qfs-dev@quantcast.com
        on_success: change
        on_failure: always
